name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check for conventional commit message
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(build|chore|ci|docs|style|refactor|perf|test)!*:'
          excludeTitle: 'false'  # optional: this excludes the title of a pull request
          error: 'You need to start your commit message with "build|chore|ci|docs|style|refactor|perf|test:"'